// generated by makeTableModule
module ArtistsTable = {
  type projectables = {
    id: int,
    name: string,
  }
  
  type optionalProjectables = {
    id: option<int>,
    name: option<string>,
  }
  
  type selectables = {
    id: Schema.column<int>,
    name: Schema.column<string>,
  }

  let t: Schema.table<projectables, optionalProjectables, selectables> = {
    name: "artists"
  }
}

// generated by makeTableModule
module AlbumsTable = {
  type projectables = {
    id: int,
    artistId: int,
    name: string,
    year: int,
  }
  
  type optionalProjectables = {
    id: option<int>,
    name: option<string>,
    artistId: option<int>,
    year: option<int>,
  }
  
  type selectables = {
    id: Schema.column<int>,
    name: Schema.column<string>,
    artistId: Schema.column<int>,
    year: Schema.column<int>,
  }
  
  let t: Schema.table<projectables, optionalProjectables, selectables> = {
    name: "albums"
  }
}

// generated by makeTableModule
module SongsTable = {
  type projectables = {
    id: int,
    albumId: int,
    name: string,
  }
  
  type optionalProjectables = {
    id: option<int>,
    albumId: option<int>,
    name: option<string>,
  }
  
  type selectables = {
    id: Schema.column<int>,
    albumId: Schema.column<int>,
    name: Schema.column<string>,
  }

  let t: Schema.table<projectables, optionalProjectables, selectables> = {
    name: "songs"
  }
}
