// generated by makeTableModule
module AlbumsTable = {
  type projectables = {
    id: int,
    name: string,
    artistId: int,
    genreId: int,
  }
  
  type optionalProjectables = {
    id: option<int>,
    name: option<string>,
    artistId: option<int>,
    genreId: option<int>,
  }
  
  type selectables = {
    id: Schema.column<int>,
    name: Schema.column<string>,
    artistId: Schema.column<int>,
    genreId: Schema.column<int>,
  }
  
  let t: Schema.table<projectables, optionalProjectables, selectables> = {
    name: "albums"
  }
}

// generated by makeTableModule
module GenresTable = {
  type projectables = {
    id: int,
    name: string,
  }
  
  type optionalProjectables = {
    id: option<int>,
    name: option<string>,
  }
  
  type selectables = {
    id: Schema.column<int>,
    name: Schema.column<string>,
  }

  let t: Schema.table<projectables, optionalProjectables, selectables> = {
    name: "genres"
  }
}

// generated by makeTableModule
module ArtistsTable = {
  type projectables = {
    id: int,
    name: string,
  }
  
  type optionalProjectables = {
    id: option<int>,
    name: option<string>,
  }
  
  type selectables = {
    id: Schema.column<int>,
    name: Schema.column<string>,
  }

  let t: Schema.table<projectables, optionalProjectables, selectables> = {
    name: "artists"
  }
}
