// generated by makeTableModule
module AlbumsTable = {
  let tableName = "albums"
  
  type projectables = {
    id: int,
    name: string,
    artistId: int,
    genreId: int,
  }
  
  type optionalProjectables = {
    id: option<int>,
    name: option<string>,
    artistId: option<int>,
    genreId: option<int>,
  }
  
  type selectables = {
    id: Column.t<int>,
    name: Column.t<string>,
    artistId: Column.t<int>,
    genreId: Column.t<int>,
  }
}

// generated by makeTableModule
module GenresTable = {
  let tableName = "genres"
  
  type projectables = {
    id: int,
    name: string,
  }
  
  type optionalProjectables = {
    id: option<int>,
    name: option<string>,
  }
  
  type selectables = {
    id: Column.t<int>,
    name: Column.t<string>,
  }
}

// generated by makeTableModule
module ArtistsTable = {
  let tableName = "artists"
  
  type projectables = {
    id: int,
    name: string,
  }
  
  type optionalProjectables = {
    id: option<int>,
    name: option<string>,
  }
  
  type selectables = {
    id: Column.t<int>,
    name: Column.t<string>,
  }
}
